window.VOCAB = [
  // ── General (Usable across all tasks) ──
  { word: "Initially", meaning: "At first; replaces the overused at the beginning", example: "Initially, I was nervous, but gradually I grew confident.", type: "General", task: "0" },
  { word: "Gradually", meaning: "Slowly over time; shows a process unfolding", example: "Gradually, I realized that hard work was paying off.", type: "General", task: "0" },
  { word: "Subsequently", meaning: "After that; more formal than then", example: "I completed my degree, and subsequently, I started working.", type: "General", task: "0" },
  { word: "Nevertheless", meaning: "Despite that; stronger contrast than but", example: "The weather was terrible; nevertheless, we went ahead with the plan.", type: "General", task: "0" },
  { word: "In hindsight", meaning: "Looking back now; great for closing reflections", example: "In hindsight, I wish I had started learning languages earlier.", type: "General", task: "0" },
  { word: "Ultimately", meaning: "In the end; finally", example: "Ultimately, the decision was mine to make.", type: "General", task: "0" },
  { word: "Perspective", meaning: "A particular way of viewing things", example: "From my perspective, this is the best approach.", type: "General", task: "0" },
  { word: "Significant", meaning: "Important or noticeable", example: "That experience had a significant impact on my life.", type: "General", task: "0" },
  { word: "Evident", meaning: "Clearly seen or understood", example: "It was evident that the project would succeed.", type: "General", task: "0" },
  { word: "Remarkable", meaning: "Worthy of attention; striking", example: "Her progress was remarkable in just a few months.", type: "General", task: "0" },

  // ── Task 1: Giving Advice ──
  { word: "That must be difficult/stressful/challenging", meaning: "Shows understanding and empathy for the person's situation", example: "That must be stressful for you, balancing so many responsibilities at once.", type: "Empathy & Understanding", task: "1" },
  { word: "I understand/appreciate how you feel", meaning: "Connects emotionally and validates their feelings", example: "I understand how frustrating that is when you've been working so hard.", type: "Empathy & Understanding", task: "1" },
  { word: "I'm confident you can", meaning: "Encouragement and belief in their ability to succeed", example: "I'm confident you can find a solution that works for your situation.", type: "Empathy & Understanding", task: "1" },
  { word: "I would recommend/suggest", meaning: "Professional and formal way to give suggestions", example: "I would recommend talking to your manager about flexible working arrangements.", type: "Suggestions & Advice", task: "1" },
  { word: "In your situation, I would", meaning: "Personalized advice that shows you understand their specific context", example: "In your situation, I would prioritize getting enough sleep before anything else.", type: "Suggestions & Advice", task: "1" },
  { word: "I think/I believe you should", meaning: "Gentle, humble way to offer advice without being preachy", example: "I think you should give yourself more credit for what you've already accomplished.", type: "Suggestions & Advice", task: "1" },
  { word: "Because/Since/As", meaning: "Introduces reasoning and explains why advice will help", example: "You should create a schedule because it will help you manage your time better.", type: "Reasoning & Explanation", task: "1" },
  { word: "This would help/benefit you by", meaning: "Shows the positive outcome or benefit of the suggestion", example: "This would help you by reducing stress and giving you a clearer plan to follow.", type: "Reasoning & Explanation", task: "1" },
  { word: "First/Second/Additionally/Also", meaning: "Transitions that connect multiple pieces of advice logically", example: "First, I'd create a schedule. Second, I would talk to your manager. Additionally, try to set aside time for yourself.", type: "Transitions & Connectors", task: "1" },
  { word: "To summarize/In summary", meaning: "Concluding phrases that recap main advice before ending", example: "To summarize, I think creating a schedule and having a conversation with your manager are your best options.", type: "Transitions & Connectors", task: "1" },
  { word: "Prudent", meaning: "Wise and careful in decision-making", example: "It's prudent to save money before making major purchases.", type: "Wisdom & Judgment", task: "1" },
  { word: "Remedy", meaning: "A solution to a problem; a treatment", example: "The best remedy for stress is regular exercise and adequate rest.", type: "Wisdom & Judgment", task: "1" },
  { word: "Elaborate", meaning: "To explain in detail or provide more information", example: "Can you elaborate on why you think that approach would work best?", type: "Wisdom & Judgment", task: "1" },
  { word: "Feasible", meaning: "Possible to do; practicable and achievable", example: "The plan is feasible if we have enough time and resources.", type: "Wisdom & Judgment", task: "1" },

  // ── Task 2: Personal Experience ──
  { word: "Exhilarating", meaning: "Thrilling and exciting", example: "Skydiving for the first time was absolutely exhilarating.", type: "Emotions & Reactions", task: "2" },
  { word: "Humbling", meaning: "Making you feel small in a meaningful way", example: "Volunteering was a humbling experience that changed me.", type: "Emotions & Reactions", task: "2" },
  { word: "Apprehensive", meaning: "Slightly anxious, unsure of what's coming", example: "I felt apprehensive before my first day at university.", type: "Emotions & Reactions", task: "2" },
  { word: "Awestruck", meaning: "Overwhelmed by something impressive or beautiful", example: "We were awestruck when we saw the Northern Lights.", type: "Emotions & Reactions", task: "2" },
  { word: "Relieved", meaning: "Free from worry after something resolves", example: "When I passed the exam, I felt completely relieved.", type: "Emotions & Reactions", task: "2" },
  { word: "Poignant", meaning: "Evoking sadness or regret; deeply moving", example: "The film had a poignant ending that touched everyone.", type: "Emotions & Reactions", task: "2" },
  { word: "Immersive", meaning: "Completely surrounding you; an immersive environment", example: "The museum created an immersive experience with interactive displays.", type: "Describing the Experience", task: "2" },
  { word: "Spontaneous", meaning: "Unplanned, happening naturally in the moment", example: "We made a spontaneous decision to drive to the coast.", type: "Describing the Experience", task: "2" },
  { word: "Surreal", meaning: "Felt strange, almost too good or odd to be real", example: "Meeting my favorite celebrity felt completely surreal.", type: "Describing the Experience", task: "2" },
  { word: "Reminisce", meaning: "To recall and think about past experiences", example: "We spent the evening reminiscing about our university days.", type: "Reflection & Lessons", task: "2" },
  { word: "Pivotal", meaning: "A turning point; a pivotal moment", example: "That conversation was a pivotal moment in my career.", type: "Reflection & Lessons", task: "2" },
  { word: "Transformative", meaning: "Changed you in a meaningful way", example: "The program was transformative for my development.", type: "Reflection & Lessons", task: "2" },
  { word: "Gratifying", meaning: "Deeply satisfying and rewarding", example: "Seeing my hard work pay off was incredibly gratifying.", type: "Reflection & Lessons", task: "2" },

  // ── Task 3: Describing a Scene ──
  { word: "In the foreground", meaning: "The closest/nearest part of the image", example: "In the foreground, I can see children playing in the park.", type: "Spatial Language", task: "3" },
  { word: "In the background", meaning: "The farthest/rear part of the image", example: "In the background, mountains are visible against the sky.", type: "Spatial Language", task: "3" },
  { word: "In the center", meaning: "The middle of the image", example: "In the center, there's a large fountain with water flowing.", type: "Spatial Language", task: "3" },
  { word: "Surrounding", meaning: "Describing things around or within other things", example: "The buildings surrounding the plaza are all historic structures.", type: "Spatial Language", task: "3" },
  { word: "Nestled", meaning: "Positioned snugly within a surrounding area", example: "Buildings nestled among the trees create a peaceful village scene.", type: "Spatial Language", task: "3" },
  { word: "Vibrant", meaning: "Bright, vivid, and full of energy", example: "The market has vibrant red and yellow colors that catch the eye.", type: "Color & Description", task: "3" },
  { word: "Vivid", meaning: "Bright and striking in appearance", example: "The vivid blue of the ocean contrasts beautifully with the white sand.", type: "Color & Description", task: "3" },
  { word: "Muted", meaning: "Soft, subtle, or understated in color", example: "The sky displayed muted tones of gray and soft blue.", type: "Color & Description", task: "3" },
  { word: "Dull", meaning: "Not bright or vivid in color", example: "The dull brown walls of the old building gave it a somber feeling.", type: "Color & Description", task: "3" },
  { word: "Pale", meaning: "Light in color, lacking intensity", example: "The pale pink sunset was reflected in the calm water.", type: "Color & Description", task: "3" },
  { word: "Bustling", meaning: "Full of busy or noisy activity and energy", example: "The bustling marketplace is crowded with vendors and shoppers moving in all directions.", type: "Atmosphere & Mood", task: "3" },
  { word: "Lively", meaning: "Full of activity and enthusiasm; animated", example: "The lively street fair had music, dancing, and happy crowds everywhere.", type: "Atmosphere & Mood", task: "3" },
  { word: "Serene", meaning: "Calm, peaceful, and undisturbed", example: "The serene lake in early morning creates a sense of tranquility and rest.", type: "Atmosphere & Mood", task: "3" },
  { word: "Peaceful", meaning: "Free from disturbance or conflict", example: "The peaceful garden with its quiet paths offers a retreat from the city.", type: "Atmosphere & Mood", task: "3" },
  { word: "Tranquil", meaning: "Calm and quiet; undisturbed", example: "The tranquil countryside landscape evokes a feeling of absolute stillness.", type: "Atmosphere & Mood", task: "3" },
  { word: "Chaotic", meaning: "In a state of complete disorder and confusion", example: "The chaotic scene at the train station showed people rushing everywhere.", type: "Atmosphere & Mood", task: "3" },
  { word: "Hectic", meaning: "Full of activity and excitement, often stressfully so", example: "The hectic office environment with constant noise and movement was overwhelming.", type: "Atmosphere & Mood", task: "3" },
  { word: "Strolling", meaning: "Walking in a leisurely, relaxed way (present continuous: are strolling)", example: "People are strolling along the boardwalk, enjoying the nice weather.", type: "Action & Movement", task: "3" },
  { word: "Wandering", meaning: "Moving aimlessly or without a fixed course (present continuous: are wandering)", example: "Visitors are wandering through the historic streets, exploring the old district.", type: "Action & Movement", task: "3" },
  { word: "Gathered", meaning: "Assembled or collected together in a group (present continuous: are gathered)", example: "People are gathered around the fountain, taking photos and chatting.", type: "Action & Movement", task: "3" },
  { word: "Adjacent", meaning: "Next to or adjoining something else", example: "The hotel is adjacent to the beach, offering easy access to the water.", type: "Describing Places & Scenes", task: "3" },
  { word: "Picturesque", meaning: "Visually attractive and charming in appearance", example: "The picturesque village with its stone cottages and cobblestone streets is stunning.", type: "Describing Places & Scenes", task: "3" },
  { word: "Sprawling", meaning: "Spreading over a large area in an extended way", example: "The sprawling garden covers several acres with trees, flowers, and pathways.", type: "Describing Places & Scenes", task: "3" },
  { word: "Desolate", meaning: "Empty, barren, and often lonely in appearance", example: "The desolate beach in early morning, with no one around, felt peaceful and isolated.", type: "Describing Places & Scenes", task: "3" },
  { word: "Crowded", meaning: "Filled with many people, often uncomfortably so", example: "The crowded marketplace is packed with shoppers moving between different stalls.", type: "Describing Places & Scenes", task: "3" },

  // ── Task 4: Making Predictions ──
  { word: "Anticipate", meaning: "To expect or predict something", example: "I anticipate that technology will transform industries.", type: "Predictions & Possibilities", task: "4" },
  { word: "Inevitable", meaning: "Certain to happen; unavoidable", example: "Change is inevitable in a fast-moving world.", type: "Predictions & Possibilities", task: "4" },
  { word: "Plausible", meaning: "Seeming reasonable or probable", example: "The explanation seems plausible but needs verification.", type: "Predictions & Possibilities", task: "4" },
  { word: "Emerging", meaning: "Beginning to appear or become known", example: "Emerging technologies are reshaping society.", type: "Predictions & Possibilities", task: "4" },
  { word: "Unprecedented", meaning: "Never done or known before; novel", example: "The pandemic presented unprecedented global challenges.", type: "Predictions & Possibilities", task: "4" },
  { word: "Likely", meaning: "Probable; probably going to happen", example: "It's likely that prices will increase next year.", type: "Predictions & Possibilities", task: "4" },
  { word: "Trajectory", meaning: "The path or direction something is following", example: "The company's growth trajectory is impressive.", type: "Predictions & Possibilities", task: "4" },
  { word: "Accelerate", meaning: "To increase in speed or intensity", example: "Climate change will accelerate if we don't act.", type: "Predictions & Possibilities", task: "4" },

  // ── Task 5: Comparing & Persuading ──
  { word: "Whereas", meaning: "In contrast to; on the other hand", example: "Whereas my brother enjoys sports, I prefer reading.", type: "Comparison & Contrast", task: "5" },
  { word: "Moreover", meaning: "In addition; furthermore", example: "The job offers great salary. Moreover, benefits are excellent.", type: "Comparison & Contrast", task: "5" },
  { word: "Analogous", meaning: "Comparable in certain respects", example: "Learning languages is analogous to learning music.", type: "Comparison & Contrast", task: "5" },
  { word: "Diverge", meaning: "To differ or move in different directions", example: "Our opinions on education diverge significantly.", type: "Comparison & Contrast", task: "5" },
  { word: "Juxtapose", meaning: "To place side by side for comparison", example: "The artist juxtaposed traditional and modern styles.", type: "Comparison & Contrast", task: "5" },
  { word: "Compelling", meaning: "Convincing and persuasive", example: "The documentary presents a compelling argument.", type: "Opinion & Persuasion", task: "5" },
  { word: "Contend", meaning: "To argue or claim firmly", example: "Experts contend that remote work boosts productivity.", type: "Opinion & Persuasion", task: "5" },
  { word: "Substantiate", meaning: "To support with evidence or proof", example: "The researcher substantiated her claims with data.", type: "Opinion & Persuasion", task: "5" },
  { word: "Entail", meaning: "To involve as a necessary consequence", example: "The job would entail relocating to another city.", type: "Cause & Effect", task: "5" },

  // ── Task 6: Difficult Situation ──
  { word: "Predicament", meaning: "A difficult, complicated, or embarrassing situation", example: "I found myself in a predicament when my car broke down.", type: "Difficulty & Challenges", task: "6" },
  { word: "Daunting", meaning: "Intimidating but not impossible", example: "Moving abroad was daunting, but I managed.", type: "Difficulty & Challenges", task: "6" },
  { word: "Persevere", meaning: "To continue steadily despite difficulty", example: "Despite obstacles, we persevered until completion.", type: "Difficulty & Challenges", task: "6" },
  { word: "Dilemma", meaning: "A situation with two equally difficult options", example: "I faced a dilemma: accept the job or stay close to family.", type: "Difficulty & Challenges", task: "6" },
  { word: "Resilience", meaning: "Ability to recover and keep going", example: "Her resilience after setbacks was truly inspiring.", type: "Difficulty & Challenges", task: "6" },
  { word: "Perseverance", meaning: "Continuing despite difficulty", example: "Her perseverance through rejection led to success.", type: "Difficulty & Challenges", task: "6" },
  { word: "Initiative", meaning: "The ability to start or lead something", example: "She took the initiative to organize the cleanup.", type: "Solutions & Strategies", task: "6" },
  { word: "Resourceful", meaning: "Clever and inventive in dealing with problems", example: "The team was resourceful with a limited budget.", type: "Solutions & Strategies", task: "6" },

  // ── Task 7: Expressing Opinions ──
  { word: "Contentious", meaning: "Causing or likely to cause heated debate", example: "Climate change remains a contentious political issue.", type: "Emotions & Reactions", task: "7" },
  { word: "Justify", meaning: "To provide good reason or explanation", example: "Can you justify why this approach is better?", type: "Opinion & Persuasion", task: "7" },
  { word: "Argue", meaning: "To give reasons for a position", example: "I argue that education should be free for all.", type: "Opinion & Persuasion", task: "7" },
  { word: "Stance", meaning: "A position or opinion on an issue", example: "Her stance on environmental issues is clear.", type: "Opinion & Persuasion", task: "7" },
  { word: "Skeptical", meaning: "Not easily convinced; doubtful", example: "I am skeptical about his promises.", type: "Opinion & Persuasion", task: "7" },
  { word: "Credible", meaning: "Able to be believed; trustworthy", example: "The source is credible and well-researched.", type: "Opinion & Persuasion", task: "7" },
  { word: "Paramount", meaning: "Of supreme importance; supreme", example: "Honesty is paramount in all relationships.", type: "Opinion & Persuasion", task: "7" },
  { word: "Cogent", meaning: "Clear, logical, and convincing", example: "The speaker made a cogent argument.", type: "Opinion & Persuasion", task: "7" },

  // ── Task 8: Unusual Situation ──
  { word: "Unprecedented", meaning: "Never done or known before; novel", example: "The situation was unprecedented in our company's history.", type: "Predictions & Possibilities", task: "8" },
  { word: "Improvise", meaning: "To create without preparation", example: "When equipment failed, the musician had to improvise.", type: "Solutions & Strategies", task: "8" },
  { word: "Unforeseen", meaning: "Not expected or anticipated", example: "An unforeseen problem delayed the project.", type: "Difficulty & Challenges", task: "8" },
  { word: "Adapting", meaning: "Adjusting to new conditions", example: "Adapting to the new system was challenging.", type: "Solutions & Strategies", task: "8" },
  { word: "Ingenious", meaning: "Clever and creative", example: "She came up with an ingenious solution.", type: "Solutions & Strategies", task: "8" },
  { word: "Bewildering", meaning: "Confusing and disorienting", example: "The situation was bewildering at first.", type: "Emotions & Reactions", task: "8" },
  { word: "Volatile", meaning: "Liable to change rapidly; unstable", example: "The situation was volatile and unpredictable.", type: "Difficulty & Challenges", task: "8" },
  { word: "Catastrophic", meaning: "Involving sudden great damage or disaster", example: "The failure would have been catastrophic.", type: "Difficulty & Challenges", task: "8" },

  // ── Task 9: Email Writing ──
  { word: "Sincerely", meaning: "In a genuine and honest way; formal closing", example: "Thank you for your help. Sincerely, John.", type: "Email Structure & Tone", task: "9" },
  { word: "Appreciate", meaning: "To recognize the value or quality of something", example: "I appreciate your quick response to my inquiry.", type: "Politeness & Courtesy", task: "9" },
  { word: "Apologies", meaning: "Expression of regret or saying sorry", example: "My apologies for the confusion in my previous message.", type: "Politeness & Courtesy", task: "9" },
  { word: "Clarify", meaning: "To make something clear or easier to understand", example: "Could you clarify what you meant by that statement?", type: "Email Communication", task: "9" },
  { word: "Formally", meaning: "In an official or ceremonial way", example: "I am writing to formally request your assistance.", type: "Email Structure & Tone", task: "9" },
  { word: "Request", meaning: "To ask for something politely or formally", example: "I request your feedback on this proposal.", type: "Email Communication", task: "9" },
  { word: "Prompt", meaning: "Done without delay; quick and efficient", example: "Thank you for your prompt attention to this matter.", type: "Politeness & Courtesy", task: "9" },
  { word: "Regarding", meaning: "Concerning; with respect to", example: "Regarding your inquiry, I can provide more details.", type: "Email Communication", task: "9" },
  { word: "Convey", meaning: "To communicate or make known", example: "I wanted to convey my sincere gratitude.", type: "Email Communication", task: "9" },
  { word: "Accommodate", meaning: "To provide lodging or adjust to suit someone's needs", example: "We can accommodate your request for a later deadline.", type: "Email Communication", task: "9" },

  // ── Task 10: Survey Response ──
  { word: "Concur", meaning: "To agree with someone or something", example: "I concur with your assessment of the situation.", type: "Agreement & Disagreement", task: "10" },
  { word: "Disagree", meaning: "To have a different opinion; not agree", example: "I respectfully disagree with that conclusion.", type: "Agreement & Disagreement", task: "10" },
  { word: "Justified", meaning: "Having good or sufficient reason; warranted", example: "Your concerns are completely justified.", type: "Reasoning & Logic", task: "10" },
  { word: "Applicable", meaning: "Relevant or suitable for a particular purpose", example: "These findings are applicable to our industry.", type: "Relevance & Importance", task: "10" },
  { word: "Constructive", meaning: "Helpful and leading to improvement", example: "The feedback was constructive and valuable.", type: "Feedback & Evaluation", task: "10" },
  { word: "Comprehensive", meaning: "Complete and thorough; covering everything", example: "The survey provided a comprehensive view of customer satisfaction.", type: "Feedback & Evaluation", task: "10" },
  { word: "Efficacy", meaning: "The ability to produce a desired result", example: "The study measured the efficacy of the new treatment.", type: "Evaluation & Results", task: "10" },
  { word: "Viable", meaning: "Capable of working successfully; feasible", example: "The proposed solution is viable and cost-effective.", type: "Evaluation & Results", task: "10" },
  { word: "Quantify", meaning: "To express in numbers or measurable terms", example: "It's difficult to quantify the impact of this change.", type: "Reasoning & Logic", task: "10" },
  { word: "Notable", meaning: "Worthy of attention; striking or remarkable", example: "There were several notable trends in the survey results.", type: "Feedback & Evaluation", task: "10" },
];
