# Generated by Django 6.0.4 on 2026-04-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('task_id', models.IntegerField()),
                ('task_name', models.CharField(max_length=100)),
                ('transcript', models.TextField(blank=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('evaluation_json', models.JSONField(blank=True, null=True)),
                ('duration_sec', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
