# Generated by Django 6.0.4 on 2026-04-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='question',
            field=models.TextField(blank=True, default=''),
        ),
    ]
