# Generated by Django 6.0.4 on 2026-04-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_attempt_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
