# Generated by Django 6.0.4 on 2026-04-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0008_backfill_sudip'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='response_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attempt',
            name='task_type',
            field=models.CharField(default='speaking', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='task_type',
            field=models.CharField(default='speaking', max_length=20),
        ),
    ]
