# Generated by Django 6.0.4 on 2026-04-16 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0009_attempt_response_text_attempt_task_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('task_id', models.IntegerField(db_index=True)),
                ('task_name', models.CharField(max_length=100)),
                ('task_type', models.CharField(default='speaking', max_length=20)),
                ('text', models.TextField()),
                ('source', models.CharField(default='ai', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='question_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='attempts.question'),
        ),
    ]
